language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    packages:
    - libfreetype6-dev
    - libgtest-dev
    - libsdl2-dev
    - imagemagick

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - mkdir -p appdir/usr/share/applications/ ; cp other/teeworlds.desktop appdir/usr/share/applications/ # FIXME; "make install" should do this
  - mkdir -p appdir/usr/share/metainfo/ ; cp other/teeworlds.appdata.xml appdir/usr/share/metainfo/ # FIXME; "make install" should do this
  - convert other/icons/teeworlds.ico -resize 512x512 teeworlds.png
  - mkdir -p appdir/usr/share/icons/hicolor/512x512/apps/ ; cp teeworlds-0.png appdir/usr/share/icons/hicolor/512x512/apps/teeworlds.png
  - ( cd appdir/usr ; ln -s ../share/teeworlds/data/ * . ) # Workaround for resources being loaded from path relative to cwd
  - wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64" -O appdir/AppRun ; chmod +x appdir/AppRun # Workaround for resources being loaded from path relative to cwd
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Teeworlds*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
